#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

service: fhir-service-validator

custom:
  stage: ${opt:stage, self:provider.stage}
  fhirVersion: ${opt:fhirVersion, '4.0.1'}
  region: ${opt:region, self:provider.region}

provider:
  name: aws
  region: us-west-2
  stage: dev
  runtime: java11
  logRetentionInDays: 3653 # 10 years
  stackTags:
    FHIR_SERVICE: 'fhir-service-validator-${self:custom.region}-${self:custom.stage}'
  tracing:
    lambda: true
  environment:
    FHIR_VERSION:
      !Ref FhirVersion
    REGION:
      !Ref Region

package:
  artifact: target/fwoa-hapi-validator-dev.jar

functions:
  uploadFHIRImplementationGuides:
    handler: uploadIGToS3.handler
    timeout: 30
    role: IGBucketLambdaRole
    runtime: nodejs14.x
    description: 'Upload implementation guides to s3'
    environment:
      IMPLEMENTATION_GUIDES_BUCKET: !Ref FHIRImplementationGuidesBucket
  validator:
    handler: software.amazon.fwoa.Handler
    role: IGBucketLambdaRole
    timeout: 25
    memorySize: 2048
#    provisionedConcurrency: 5

resources:
  - Parameters:
      Stage:
        Type: String
        Default: ${self:custom.stage}
        Description: 'The deployment stage (e.g. dev, qa, prod). Default: dev'
      FhirVersion:
        Type: String
        Default: ${self:custom.fhirVersion}
        AllowedValues:
          - '4.0.1'
          - '3.0.1'
        Description: 'The FHIR version used by the validator. Default: 4.0.1'
      Region:
        Type: String
        Default: ${self:custom.region}
        AllowedValues:
          - 'us-east-2'
          - 'us-east-1'
          - 'us-west-1'
          - 'us-west-2'
          - 'af-south-1'
          - 'ap-east-1'
          - 'ap-south-1'
          - 'ap-northeast-3'
          - 'ap-northeast-2'
          - 'ap-northeast-1'
          - 'ap-southeast-1'
          - 'ap-southeast-2'
          - 'ca-central-1'
          - 'eu-central-1'
          - 'eu-west-1'
          - 'eu-west-2'
          - 'eu-west-3'
          - 'eu-south-1'
          - 'eu-north-1'
          - 'me-south-1'
          - 'sa-east-1'
          - 'us-gov-east-1'
          - 'us-gov-west-1'
  # - Outputs:
  #     ValidatorLambdaAlias:
  #       Description: Validator lambda function alias
  #       Value: !Ref ValidatorProvConcLambdaAlias # serverless by convention capitalizes first letter and suffixes with "ProvConcLambdaAlias"
  #       Export:
  #         Name: !Join ['-', ['fhir-service-validator-lambda', !Ref Stage]]
  - Resources:
      FHIRImplementationGuidesBucket:
        Type: AWS::S3::Bucket
        DeletionPolicy: Retain
        UpdateReplacePolicy: Retain
      IGBucketLambdaRole:
        Type: AWS::IAM::Role
        Properties:
          AssumeRolePolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Principal:
                  Service:
                    - lambda.amazonaws.com
                Action:
                  - sts:AssumeRole
          ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
            - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
          Policies:
            - PolicyName: s3Access
              PolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Action:
                      - s3:PutObject
                      - s3:GetObject
                      - s3:ListObjectsV2
                      - s3:ListBuckets
                      - s3:DeleteObject
                      - s3:*
                    Resource: !Join ['', ['arn:aws:s3:::', !Ref FHIRImplementationGuidesBucket, '/*']]