#
#  Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
#  SPDX-License-Identifier: Apache-2.0
#

service: fhir-service-validator

plugins:
  - serverless-plugin-scripts
custom:
  stage: ${opt:stage, self:provider.stage}
  fhirVersion: ${opt:fhirVersion, '4.0.1'}
  region: ${opt:region, self:provider.region}
  # scripts:
  #   hooks:
  #     'before:deploy:deploy': node uploadIGToS3.js ${self:custom.region}

provider:
  name: aws
  region: us-west-2
  stage: dev
  runtime: java11
  logRetentionInDays: 3653 # 10 years
  stackTags:
    FHIR_SERVICE: 'fhir-service-validator-${self:custom.region}-${self:custom.stage}'
  tracing:
    lambda: true
  environment:
    FHIR_VERSION:
      !Ref FhirVersion
    REGION:
      !Ref Region
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:listObjectsV2"
        - "s3:getObject"
        - "s3:invoke"
        - "s3:*"
      Resource: 
        - "arn:aws:s3:::fhir-service-validator-implementationguides"
        - "arn:aws:s3:::fhir-service-validator-implementationguides/*"

package:
  artifact: target/fwoa-hapi-validator-dev.jar

functions:
  validator:
    handler: software.amazon.fwoa.Handler
    timeout: 25
    memorySize: 2048
    provisionedConcurrency: 5

resources:
  - Parameters:
      Stage:
        Type: String
        Default: ${self:custom.stage}
        Description: 'The deployment stage (e.g. dev, qa, prod). Default: dev'
      FhirVersion:
        Type: String
        Default: ${self:custom.fhirVersion}
        AllowedValues:
          - '4.0.1'
          - '3.0.1'
        Description: 'The FHIR version used by the validator. Default: 4.0.1'
      Region:
        Type: String
        Default: ${self:custom.region}
        AllowedValues:
          - 'us-east-2'
          - 'us-east-1'
          - 'us-west-1'
          - 'us-west-2'
          - 'af-south-1'
          - 'ap-east-1'
          - 'ap-south-1'
          - 'ap-northeast-3'
          - 'ap-northeast-2'
          - 'ap-northeast-1'
          - 'ap-southeast-1'
          - 'ap-southeast-2'
          - 'ca-central-1'
          - 'eu-central-1'
          - 'eu-west-1'
          - 'eu-west-2'
          - 'eu-west-3'
          - 'eu-south-1'
          - 'eu-north-1'
          - 'me-south-1'
          - 'sa-east-1'
          - 'us-gov-east-1'
          - 'us-gov-west-1'
  - Outputs:
      ValidatorLambdaAlias:
        Description: Validator lambda function alias
        Value: !Ref ValidatorProvConcLambdaAlias # serverless by convention capitalizes first letter and suffixes with "ProvConcLambdaAlias"
        Export:
          Name: !Join ['-', ['fhir-service-validator-lambda', !Ref Stage]]